pycodestyle:  # Valid if scanner.linter is pycodestyle
    max-line-length: 79
    ignore:
        - E121
        - E123
        - E126
        - E226
        - E24
        - E704
        - W503
        - W504
        - E203
    exclude:
        - */migrations/
