[tool.black]
line-length = 79

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
exclude = [
    "migrations"
]
namespace_packages = true

[tool.django-stubs]
django_settings_module = "nabweb.settings"
