# Generated by Django 2.1.3 on 2018-11-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.TextField(default='botsin.space')),
                ('client_id', models.TextField(null=True)),
                ('client_secret', models.TextField(null=True)),
                ('redirect_uri', models.TextField(null=True)),
                ('access_token', models.TextField(null=True)),
                ('username', models.TextField(null=True)),
                ('display_name', models.TextField(null=True)),
                ('avatar', models.TextField(null=True)),
                ('spouse_handle', models.TextField(null=True)),
                ('spouse_pairing_state', models.TextField(null=True)),
                ('spouse_pairing_date', models.DateTimeField(null=True)),
                ('spouse_left_ear_position', models.IntegerField(null=True)),
                ('spouse_right_ear_position', models.IntegerField(null=True)),
                ('last_processed_status_id', models.IntegerField(null=True)),
                ('last_processed_status_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
