# Generated by Django 2.1.3 on 2018-11-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabmastodond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='last_processed_status_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
