# Generated by Django 3.0.1 on 2020-02-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabmastodond', '0002_auto_20181112_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='instance',
            field=models.TextField(default='mstdn.fr'),
        ),
    ]
