# Generated by Django 3.0.7 on 2020-06-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabmastodond', '0003_auto_20200205_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='instance',
            field=models.TextField(),
        ),
    ]
