# Generated by Django 3.1.12 on 2022-05-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabiftttd", "0002_auto_20220525_0848"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="json_data_base",
            field=models.TextField(default="", null=True),
        ),
    ]
