# Generated by Django 3.0.7 on 2021-03-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabweatherd', '0006_config_location_user_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='weather_frequency',
            field=models.TextField(default='0', null=True),
        ),
    ]
