# Generated by Django 3.0.14 on 2021-05-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabweatherd", "0011_auto_20210510_0944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="weather_animation_type",
            field=models.TextField(default="weather_and_rain", null=True),
        ),
    ]
