# Generated by Django 3.0.14 on 2021-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabweatherd', '0012_auto_20210509_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='location',
            field=models.TextField(default='{"insee": "29039", "name": "Concarneau", "lat": 47.87528, "lon": -3.91889,     "country": "FR", "admin": "Bretagne", "admin2": "29", "postCode": "29900"}', null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='location_user_friendly',
            field=models.TextField(default='    Concarneau - Bretagne (29) - FR'),
        ),
    ]
