version: '3.8'
services:
    # PostgreSQL database
    db:
        image: postgres:11-alpine
        environment:
            POSTGRES_PASSWORD: pynab
            POSTGRES_USER: pynab
        volumes:
            - var-lib-postgresql-data:/var/lib/postgresql/data
            - var-run-postgresql:/var/run/postgresql
    # Once off container to run the DB migrations
    migrate:
        build: ./nab
        volumes:
            - ../:/home/pi/pynab
            - var-run-postgresql:/var/run/postgresql
        depends_on:
            - db
        command: ["/bin/bash", "/usr/local/bin/run-migrate.sh"]
    nabdevd:
        image: registry.gitlab.com/nguillaumin/nabdevd:latest
        ports:
            - 3000:3000
    nabweb:
        build: ./nab
        volumes:
            - ../:/home/pi/pynab
            - var-run-postgresql:/var/run/postgresql
        depends_on:
            - db
            - migrate
            - nabdevd
        command: ["/bin/sh", "-c", "/home/pi/venv/bin/gunicorn --timeout 60 -b 0.0.0.0 nabweb.wsgi"]
        ports:
            - 8000:8000
    nab8balld:
        build: ./nab
        volumes:
            - ../:/home/pi/pynab
            - var-run-postgresql:/var/run/postgresql
        depends_on:
            - db
            - migrate
            - nabdevd
        command: ["/bin/bash", "/usr/local/bin/run-service.sh", "nab8balld.nab8balld"]
    nabairqualityd:
        build: ./nab
        volumes:
            - ../:/home/pi/pynab
            - var-run-postgresql:/var/run/postgresql
        depends_on:
            - db
            - migrate
            - nabdevd
        command: ["/bin/bash", "/usr/local/bin/run-service.sh", "nabairqualityd.nabairqualityd"]
    nabbookd:
        build: ./nab
        volumes:
            - ../:/home/pi/pynab
            - var-run-postgresql:/var/run/postgresql
        depends_on:
            - db
            - migrate
            - nabdevd
        command: ["/bin/bash", "/usr/local/bin/run-service.sh", "nabbookd.nabbookd"]
    nabclockd:
        build: ./nab
        volumes:
            - ../:/home/pi/pynab
            - var-run-postgresql:/var/run/postgresql
        depends_on:
            - db
            - migrate
            - nabdevd
        command: ["/bin/bash", "/usr/local/bin/run-service.sh", "nabclockd.nabclockd"]
    nabsurprised:
        build: ./nab
        volumes:
            - ../:/home/pi/pynab
            - var-run-postgresql:/var/run/postgresql
        depends_on:
            - db
            - migrate
            - nabdevd
        command: ["/bin/bash", "/usr/local/bin/run-service.sh", "nabsurprised.nabsurprised"]
    nabtaichid:
        build: ./nab
        volumes:
            - ../:/home/pi/pynab
            - var-run-postgresql:/var/run/postgresql
        depends_on:
            - db
            - migrate
            - nabdevd
        command: ["/bin/bash", "/usr/local/bin/run-service.sh", "nabtaichid.nabtaichid"]
    nabweatherd:
        build: ./nab
        volumes:
            - ../:/home/pi/pynab
            - var-run-postgresql:/var/run/postgresql
        depends_on:
            - db
            - migrate
            - nabdevd
        command: ["/bin/bash", "/usr/local/bin/run-service.sh", "nabweatherd.nabweatherd"]
    nabmastodond:
        build: ./nab
        volumes:
            - ../:/home/pi/pynab
            - var-run-postgresql:/var/run/postgresql
        depends_on:
            - db
            - migrate
            - nabdevd
        command: ["/bin/bash", "/usr/local/bin/run-service.sh", "nabmastodond.nabmastodond"]

volumes:
    # Share the PostgreSQL socket between containers
    var-run-postgresql:
    # Persist the PostgreSQL data across restarts
    var-lib-postgresql-data:
