# Generated by Django 3.2.13 on 2022-06-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabclockd", "0003_alter_config_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="sleep_wakeup_override",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
