# Generated by Django 2.2.7 on 2019-12-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nabairqualityd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='location',
            new_name='index_airquality',
        ),
    ]
