# Generated by Django 3.0.14 on 2021-05-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabairqualityd", "0005_auto_20200612_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="visual_airquality",
            field=models.TextField(default="always", null=True),
        ),
    ]
