# Generated by Django 3.2.13 on 2022-06-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabairqualityd", "0007_alter_config_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="localisation",
        ),
        migrations.AddField(
            model_name="config",
            name="localisation",
            field=models.JSONField(null=True),
        ),
    ]
