# Generated by Django 3.2.15 on 2022-11-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabradio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="json_data_base",
            field=models.TextField(default="", null=True),
        ),
    ]
